// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Phase11_ASP.SQLHandler;

namespace Phase11_ASP.Migrations
{
    [DbContext(typeof(InvertedIndexContext))]
    partial class InvertedIndexContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "6.0.0-preview.5.21301.9")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("DocumentWord", b =>
                {
                    b.Property<int>("DocsCollectionid")
                        .HasColumnType("int");

                    b.Property<int>("wordsCollectionid")
                        .HasColumnType("int");

                    b.HasKey("DocsCollectionid", "wordsCollectionid");

                    b.HasIndex("wordsCollectionid");

                    b.ToTable("DocumentWord");
                });

            modelBuilder.Entity("Phase11_ASP.Models.Document", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("DocContents")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DocName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("id");

                    b.ToTable("DocumentsDbContext");
                });

            modelBuilder.Entity("Phase11_ASP.Models.Word", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Content")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("id");

                    b.ToTable("WordsDbContext");
                });

            modelBuilder.Entity("DocumentWord", b =>
                {
                    b.HasOne("Phase11_ASP.Models.Document", null)
                        .WithMany()
                        .HasForeignKey("DocsCollectionid")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Phase11_ASP.Models.Word", null)
                        .WithMany()
                        .HasForeignKey("wordsCollectionid")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
